export const AppConstant = {
    URL: "http://localhost:5000/api/v1/",
    JWT_STORING_KEY: "JWT_ACCESS_KEY",
    JWT_STORING_REFRESH_KEY: "JWT_REFRESH_KEY",
    PRIORITY_STORING_KEY: "PRIORITY_VALUES",
    STATUS_STORING_KEY: "STATUS_VALUES"
}